before_install:
  - export LLVM=/usr/lib/llvm-3.2/bin
  - sudo add-apt-repository ppa:h-rayflood/llvm -y
  - sudo apt-get update -y
  - sudo apt-get install llvm-3.2 clang-3.2 bison gperf -y
  - git clone git://github.com/xxuejie/webruby.git
  # webruby config
  - cd webruby
  - git submodule update --init
  # Lets emcc sets up the environment
  - gem build webruby.gemspec
  - mv `ls webruby-*.gem` webruby-latest.gem
  - gem install --no-ri --no-rdoc ./webruby-latest.gem
  - cd ..
  # create sample project
  - webruby new SampleProject
  - cd SampleProject
  - echo "Webruby::App.setup { |c| c.gem \"/home/travis/build/xxuejie/mruby-js\" }" >> Rakefile
  # Just copy-paste version of fix from https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script: "rake && rake mrbtest"
