env:
  - LLVM=/usr/lib/llvm-3.2/bin
  - EMSCRIPTEN_DIR=/home/travis/build/xxuejie/mruby-js/webruby/modules/emscripten
  - BUILD_CONFIG=/home/travis/build/xxuejie/mruby-js/config/test_config.rb
before_install:
  - sudo add-apt-repository ppa:h-rayflood/llvm -y
  - sudo apt-get update -y
  - sudo apt-get install llvm-3.2 clang-3.2 -y
  - git clone git://github.com/xxuejie/webruby.git
  - cd webruby
  - git submodule update --init
  # Lets emcc sets up the environment
  - ./modules/emscripten/emcc
  # Just copy-paste version of fix from https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script: "rake mrbtest"
